apiVersion: v1
kind: Pod
metadata:
  name: orchestral-dancer
  namespace: orchestral
spec:
  containers:
    - name: orchestral-lover
      image: nginx
      annotations:
        description: "Orchestral pod"
        owner: "Emanuel Arturo Rivas Escobar"
        contact: "emanuel.rivas@correounivalle.edu.co"
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "orchestral-vibes"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: "In"
                values:
                  - "orchestral"