apiVersion: v1
kind: Pod
metadata:
  name: perreador-maximo
  namespace: reggaeton
  annotations:
    description: "Reggaeton pod"
    owner: "Daniel Arias Castrillon"
    contact: "daniel.arias.castrillon@correounivalle.edu.co"
spec:
  containers:
    - name: reggaetonero
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano
